#!/bin/sh

HOMEPATH="${HOMEPATH:-$HOME/.callofduty}"
BINDIR="${BINDIR:-$HOME/opt/cod}"
basepath="$BINDIR"

binary_name='cod_lnxded'
gamepath="$HOMEPATH/main"
if test "$UO" -gt 0 2> /dev/null ; then
	binary_name='coduo_lnxded'
	gamepath="$HOMEPATH/uo"
fi

mkdir --parents "$gamepath"
touch "$gamepath/console_mp_server.log" "$gamepath/games_mp.log"

# Mix output of logs with server output. Console log outputs extra errors.
tail --follow "$gamepath/console_mp_server.log" | sed -nE '/^[\*]+/,/^[\*]+/p' &
tail --follow "$gamepath/games_mp.log" &

"$BINDIR/$binary_name" +set fs_basepath "$basepath" +set fs_homepath "$HOMEPATH" "$@"

# Echo breaks sometimes after server segfault.
stty echo

# Kill backgrounded processes from this session (tail).
jobs -p | xargs kill
