#!/bin/sh

BASEPATH="${BASEPATH:-$HOME/opt/cod-windows}"

binary_name='CoDMP.exe'
mainpath="$BASEPATH/main"
if test "$UO" -gt 0 2> /dev/null ; then
	binary_name='CoDUOMP.exe'
	mainpath="$BASEPATH/uo"
fi

touch "$mainpath/console_mp.log" "$mainpath/games_mp.log"

# Mix output of logs with server output. Console log outputs extra errors.
tail --follow "$mainpath/console_mp.log" &
tail --follow "$mainpath/games_mp.log" &

cd "$BASEPATH"

WINEDEBUG=fixme-all MESA_EXTENSION_MAX_YEAR=2004 __GL_ExtensionStringVersion=17700 wine "$binary_name" "$@"

# Kill backgrounded processes from this session (tail).
jobs -p | xargs kill
