#!/bin/sh

BASEPATH="${BASEPATH:-$HOME/.wine/drive_c/Program Files (x86)/Call of Duty Server}"

touch "$BASEPATH/main/console_mp.log" "$BASEPATH/main/games_mp.log"

# Mix output of logs with server output. Console log outputs extra errors.
tail --follow "$BASEPATH/main/console_mp.log" &
tail --follow "$BASEPATH/main/games_mp.log" &

cd "$BASEPATH"

WINEDEBUG=fixme-all MESA_EXTENSION_MAX_YEAR=2004 __GL_ExtensionStringVersion=17700 wine "CoDMP.exe" "$@"

# Kill backgrounded processes from this session (tail).
jobs -p | xargs kill
